# Generated by Django 3.2.25 on 2025-07-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('biscuits', 'Biscuits'), ('drinks', 'Drinks')], default='drinks', max_length=50),
        ),
    ]
