# Generated by Django 3.2.25 on 2025-07-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('biscuits', 'Biscuits'), ('drinks', 'Drinks')], default='drinks', max_length=30),
        ),
    ]
